package chat.network;

public interface IStatusCodes {
    String EXISTING_LOGIN = "ALREADY_EXISTING_LOGIN";
    String NONEXISTENT_LOGIN = "NONEXISTENT_LOGIN";

    String REGISTRATION_TOKEN = "REGISTRATION_TOKEN";
    String REGISTRATION_SUCCESS_TOKEN = "SUCCESS_REGISTRATION";

    String LOGIN_TOKEN = "LOGIN_TOKEN";
    String WRONG_PASSWORD = "WRONG_PASSWORD";
    String TO_CHAT = "TO_CHAT";

    String DUAL_CONNECTION_BLOCK = "DUAL_CONNECTION_BLOCK";
    String SPACES_ERROR = "NO_SPACES_IN_LOGIN_AND_PASSWORD";
    String DISCONNECT_TOKEN = "DISCONNECT_TOKEN";

    String SIMPLE_MESSAGE_TOKEN = "SIMPLE_MESSAGE_TOKEN";
    String PRIVATE_MESSAGE_TOKEN = "PRIVATE_MESSAGE_TOKEN";

    String NOT_AUTHENTICATION_REQUEST = "NOT_AUTHENTICATION_REQUEST";
    String EMPTY_REQUEST = "EMPTY_REQUEST";

    String ONLINE_LIST_REFRESH = "ONLINE_LIST_REFRESH";
}
